<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings')->delete();
        
        \DB::table('settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Home Page Background Image',
                'key' => 'home_page_background_image',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'home_page',
                'created_at' => '2017-12-21 11:34:36',
                'updated_at' => '2017-12-26 12:58:23',
                'value_image_file_name' => 'landing-bg.jpg',
                'value_image_file_size' => 896521,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 12:58:23',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'About Page Image',
                'key' => 'about_page_image',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'about_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-26 13:44:28',
                'value_image_file_name' => 'hqdefault.jpg',
                'value_image_file_size' => 8256,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 13:44:28',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'About Page Video',
                'key' => 'about_page_video',
                'value' => 'https://www.youtube.com/watch?v=C0DPdy98e4c',
                'type' => 'text',
                'namespace' => 'about_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-26 13:44:28',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'About Page Title 1',
                'key' => 'about_page_title1',
                'value' => 'Welcome to hydeout',
                'type' => 'text',
                'namespace' => 'about_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-21 14:45:41',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'About Page Content 1',
                'key' => 'about_page_content1',
                'value' => 'The one and only venue that offers countless entertaining, relaxing and amusing activities for each and every member of the family. Hyde Out is the place where you can play, shop, dine and entertain; or do nothing and enjoy the tranquillity of green open spaces that have been developed to create the escape you need from the chaos of the city.',
                'type' => 'content',
                'namespace' => 'about_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-21 15:45:12',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'About Page Title 2',
                'key' => 'about_page_title2',
                'value' => 'Partners',
                'type' => 'text',
                'namespace' => 'about_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-21 11:34:37',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'About Page Content 2',
                'key' => 'about_page_content2',
                'value' => '
Hyde Out is proud to host Cairo’s very best performance shows, events and vendors. To guarantee an unrivalled entertainment experience, we’ve partnered with Egypt’s most prominent and exclusive amusement and showbiz companies.',
                'type' => 'content',
                'namespace' => 'about_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-21 11:34:37',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Map Page GIF',
                'key' => 'map_page_gif',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'map_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-24 16:08:09',
                'value_image_file_name' => 'location.png',
                'value_image_file_size' => 336336,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-24 16:08:09',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Map Page content',
                'key' => 'map_page_content',
                'value' => 'The one and only venue that offers countless entertaining, relaxing and amusing activities for each and every member of the family. Hyde Out is the place where you can play, shop, dine and entertain; or do nothing and enjoy the tranquillity of green open spaces that have been developed to create the escape you need from the chaos of the city',
                'type' => 'content',
                'namespace' => 'map_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-24 16:08:25',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Explore Page Image 1',
                'key' => 'explore_page_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-25 10:26:07',
                'value_image_file_name' => 'play-bg.jpg',
                'value_image_file_size' => 152317,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:26:07',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Explore Page Image 2',
                'key' => 'explore_page_image2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-25 10:30:14',
                'value_image_file_name' => 'picnic-bg.jpg',
                'value_image_file_size' => 91081,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:30:14',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Explore Page Image 3',
                'key' => 'explore_page_image3',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:37',
                'updated_at' => '2017-12-25 10:31:23',
                'value_image_file_name' => 'entertain-bg.jpg',
                'value_image_file_size' => 112489,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:31:23',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Explore Page Image 4',
                'key' => 'explore_page_image4',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 10:32:07',
                'value_image_file_name' => 'eat-drink-bg.jpg',
                'value_image_file_size' => 51513,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:32:07',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Explore Page Image 5',
                'key' => 'explore_page_image5',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 10:32:43',
                'value_image_file_name' => 'pet-time-bg.jpg',
                'value_image_file_size' => 43510,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:32:43',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Explore Page Image 6',
                'key' => 'explore_page_image6',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 10:33:06',
                'value_image_file_name' => 'exercise-bg.jpg',
                'value_image_file_size' => 42951,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:33:06',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Explore Page Image 7',
                'key' => 'explore_page_image7',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 10:33:41',
                'value_image_file_name' => 'shop-bg.jpg',
                'value_image_file_size' => 37931,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 10:33:41',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Explore Page Title',
                'key' => 'explore_page_title',
                'value' => 'Title',
                'type' => 'text',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-21 13:48:41',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Explore Page Url',
                'key' => 'explore_page_url',
                'value' => 'link',
                'type' => 'text',
                'namespace' => 'explore_page',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-21 11:34:38',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Explore Elements Play Title 1',
                'key' => 'explore_elements_play_title1',
                'value' => 'It’s play time!',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 10:58:39',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Explore Elements Play Content 1',
                'key' => 'explore_elements_play_content1',
                'value' => 'Hyde Out’s Kids’ Park is the perfect place for the young ones to climb, run and tumble. Let them play and explore in an exciting and safe environment that’ll fill them with joy and nurture their basic skills. We encourage every member of the family to play, that’s why Hyde Out has designated play areas for adults, featuring a wide selection of challenging and adventurous games and activities.',
                'type' => 'content',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 10:59:37',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Explore Elements Play Image 1',
                'key' => 'explore_elements_play_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 11:13:59',
                'value_image_file_name' => 'play-show-bg.jpg',
                'value_image_file_size' => 232188,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 11:13:59',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Explore Elements Play Provider Logo',
                'key' => 'explore_elements_play_provider_logo',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 11:14:34',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-25 11:14:34',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Explore Elements Play Provider Title',
                'key' => 'explore_elements_play_provider_title',
                'value' => 'FAGNOON',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 11:31:12',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Explore Elements Play  Provider Content',
                'key' => 'explore_elements_play_provider_content',
                'value' => 'FAGNOON is a designated zone spread over 6000 sqm. In Hyde Out where convenient games are available like Paintball, Aqua Fight, Laser Fight, Bazooka Fight, and which are targeting young professionals, families and kids, university students and youth.',
                'type' => 'content',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 11:31:34',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Explore Elements Play Working Hours1',
                'key' => 'explore_elements_play_working_hours1',
                'value' => 'Sunday - Wednesday: from 14:00 to 21:00',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-25 11:40:41',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Explore Elements Play Provider Site',
                'key' => 'explore_elements_play_provider_site',
                'value' => 'www.fagnoon.com',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 09:54:48',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Explore Elements Play Location ',
                'key' => 'explore_elements_play_location',
                'value' => 'text',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-21 11:34:38',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Explore Elements picnic Title 1',
                'key' => 'explore_elements_picnic_title1',
                'value' => 'Eat Al Fresco in the inspiring outdoors!',
                'type' => 'text',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:01:26',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Explore Elements picnic Content 1',
                'key' => 'explore_elements_picnic_content1',
                'value' => 'Picnics are an all-time favourite activity enjoyed by
millions of people around the world. Today you can
enjoy a most fascinating picnic experience in the
heart of New Cairo, as Hyde Out’s Picnic Park
opens its doors to introduce a new concept that
celebrates get-togethers and special times with
family and friends.',
                'type' => 'content',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:03:01',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Explore Elements picnic Content 2',
                'key' => 'explore_elements_picnic_content2',
                'value' => 'Overlooking the lake and surrounded by lush
greenery, the Picnic Park is specifically designed to
turn your picnic into a perfect day out with the
family. Pack your picnic basket and mat, and bring
along your family, friends and pets to enjoy a day
out at Hyde Out’s Picnic Park.',
                'type' => 'content',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:03:21',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Explore Elements picnic Image 1',
                'key' => 'explore_elements_picnic_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:13:19',
                'value_image_file_name' => 'picnic-show-bg-01.jpg',
                'value_image_file_size' => 283036,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:13:19',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Explore Elements picnic Image 2',
                'key' => 'explore_elements_picnic_image2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:13:37',
                'value_image_file_name' => 'picnic-show-bg-02.jpg',
                'value_image_file_size' => 137077,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:13:37',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Explore Elements picnic Provider Logo',
                'key' => 'explore_elements_picnic_provider_logo',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 14:34:33',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 14:34:33',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Explore Elements picnic Provider Title',
                'key' => 'explore_elements_picnic_provider_title',
                'value' => 'Al Fresco',
                'type' => 'text',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:04:42',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Explore Elements picnic  Provider Content',
                'key' => 'explore_elements_picnic_provider_content',
                'value' => 'Al Fresco is a designated zone spread
over 6000 sqm. In Hyde Out where
convenient games are available like
Paintball, Aqua Fight, Laser Fight,
Bazooka Fight, and which are targeting
young professionals, families and kids,
university students and youth.',
                'type' => 'content',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:05:00',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Explore Elements picnic Working Hours1',
                'key' => 'explore_elements_picnic_working_hours1',
                'value' => 'Sunday - Thursday: from 10:00 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:06:13',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Explore Elements picnic Provider Site',
                'key' => 'explore_elements_picnic_provider_site',
                'value' => 'Website',
                'type' => 'text',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-21 11:34:38',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'Explore Elements pet time Title 1',
                'key' => 'explore_elements_pet_time_title1',
                'value' => 'It\'s Pet Time!',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 11:10:28',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'Explore Elements pet time Content 1',
                'key' => 'explore_elements_pet_time_content1',
                'value' => 'Hyde Out is a pet-friendly venue, which means there’s no reason to leave your furry friends at home when you’re out having a good time – they’re family after all! Bring your dog for a walk along the lake or enjoy a picnic and game of Frisbee in the park.',
                'type' => 'content',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 11:10:39',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'Explore Elements pet time Image 1',
                'key' => 'explore_elements_pet_time_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:11:08',
                'value_image_file_name' => 'pet-show-bg-01.jpg',
                'value_image_file_size' => 238990,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 11:11:08',
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'Explore Elements pet time Image 2',
                'key' => 'explore_elements_pet_time_image2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:11:24',
                'value_image_file_name' => 'pet-show-bg-02.jpg',
                'value_image_file_size' => 98408,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 11:11:24',
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'Explore Elements pet time Provider Logo',
                'key' => 'explore_elements_pet_time_provider_logo',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:13:34',
                'value_image_file_name' => 'sponsor-logo-02.png',
                'value_image_file_size' => 13401,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 11:13:34',
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'Explore Elements pet time Provider Title',
                'key' => 'explore_elements_pet_time_provider_title',
                'value' => 'K-9 SENSE',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:16:32',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Explore Elements pet time Location ',
                'key' => 'explore_elements_pet_time_location',
                'value' => 'text',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-21 11:34:39',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Explore Elements exercise Title 1',
                'key' => 'explore_elements_exercise_title1',
                'value' => 'Rejuvenate your Energy in the Heart of Nature!',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:55:30',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Explore Elements exercise Content 1',
                'key' => 'explore_elements_exercise_content1',
                'value' => 'Once you’re done with your fitness regimen,
treat yourself to a nutritious meal or
snack at Hyde Out’s designated health
and fitness restaurant. If you’d rather
grab a nutritious snack on the go, there
are several healthy food options offered
by the food trucks, food carts and juice
bars at Hyde Out’s Park Food Area',
                'type' => 'content',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:55:43',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Explore Elements exercise Image 1',
                'key' => 'explore_elements_exercise_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:56:03',
                'value_image_file_name' => 'exercise-show-bg-01.jpg',
                'value_image_file_size' => 145994,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 11:56:03',
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Explore Elements exercise Image 2',
                'key' => 'explore_elements_exercise_image2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:56:31',
                'value_image_file_name' => 'exercise-show-bg-02.jpg',
                'value_image_file_size' => 84498,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 11:56:31',
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Explore Elements exercise Provider Logo',
                'key' => 'explore_elements_exercise_provider_logo',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:56:56',
                'value_image_file_name' => 'sponsor-logo-03.png',
                'value_image_file_size' => 22234,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 11:56:56',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Explore Elements exercise Provider Title',
                'key' => 'explore_elements_exercise_provider_title',
                'value' => 'crossfit',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:57:32',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'Explore Elements exercise  Provider Content',
                'key' => 'explore_elements_exercise_provider_content',
                'value' => 'Treat your mind, body and soul by exercising
at Hyde Out’s Fitness Centre or in the outdoors
to reconnect with nature. Explore the
trails and paths of Hyde Out as you enjoy a
quick jog in the park, or bring your exercise
mat and meditate as you embrace the healing
and relaxing sensations of the serene
surrounding nature.',
                'type' => 'content',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:57:49',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'Explore Elements exercise Working Hours1',
                'key' => 'explore_elements_exercise_working_hours1',
                'value' => 'Sunday - Wednesday: from 14:00 to 21:00',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 11:59:58',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'Explore Elements exercise Provider Site',
                'key' => 'explore_elements_exercise_provider_site',
                'value' => 'www.crossfitstars.com',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 12:00:46',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'Explore Elements exercise Location ',
                'key' => 'explore_elements_exercise_location',
                'value' => 'text',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-21 11:34:39',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'Explore Elements eat and drink the promenade Title 1',
                'key' => 'explore_elements_eat_and_drink_the_promenade_title1',
                'value' => 'Take a break and gratify your taste buds in the heart of nature!',
                'type' => 'text',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:47:07',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'Explore Elements eat and drink the promenade Logo 1',
                'key' => 'explore_elements_eat_and_drink_the_promenade_logo1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:51:49',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:51:49',
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'Explore Elements eat and drink the promenade Logo 2',
                'key' => 'explore_elements_eat_and_drink_the_promenade_logo2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:52:24',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:52:24',
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'Explore Elements eat and drink the promenade Logo 3',
                'key' => 'explore_elements_eat_and_drink_the_promenade_logo3',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:52:47',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:52:47',
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'Explore Elements eat and drink the promenade Logo 4',
                'key' => 'explore_elements_eat_and_drink_the_promenade_logo4',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:53:09',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:53:09',
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'Explore Elements eat and drink the promenade Logo 5',
                'key' => 'explore_elements_eat_and_drink_the_promenade_logo5',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:53:47',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:53:47',
            ),
            60 => 
            array (
                'id' => 62,
                'name' => 'Explore Elements eat and drink the promenade Logo 6',
                'key' => 'explore_elements_eat_and_drink_the_promenade_logo6',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:54:20',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:54:20',
            ),
            61 => 
            array (
                'id' => 63,
                'name' => 'Explore Elements eat and drink the promenade Content 1',
                'key' => 'explore_elements_eat_and_drink_the_promenade_content1',
                'value' => 'Al Fresco is a designated zone spread
over 6000 sqm. In Hyde Out where
convenient games are available like
Paintball, Aqua Fight, Laser Fight,
Bazooka Fight, and which are targeting
young professionals, families and
kids, university students and youth.',
                'type' => 'content',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:47:26',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'name' => 'Explore Elements eat and drink the promenade Image 1',
                'key' => 'explore_elements_eat_and_drink_the_promenade_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:57:39',
                'value_image_file_name' => 'promenade-show-bg-02.jpg',
                'value_image_file_size' => 129766,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:57:39',
            ),
            63 => 
            array (
                'id' => 65,
                'name' => 'Explore Elements eat and drink the promenade Image 2',
                'key' => 'explore_elements_eat_and_drink_the_promenade_image2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:58:05',
                'value_image_file_name' => 'promenade-show-bg-01.jpg',
                'value_image_file_size' => 278822,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:58:05',
            ),
            64 => 
            array (
                'id' => 66,
                'name' => 'Explore Elements eat and drink the promenade Title 2',
                'key' => 'explore_elements_eat_and_drink_the_promenade_title2',
                'value' => 'THE PROMENADE',
                'type' => 'text',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:48:33',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 67,
                'name' => 'Explore Elements eat and drink the promenade Content 2',
                'key' => 'explore_elements_eat_and_drink_the_promenade_content2',
                'value' => 'Hyde Out’s Promenade is the place to go to satisfy
your every culinary desire. Lined with a wide selection
of cafés and restaurants, the Promenade has
something to offer for everyone, including healthy
foods and snacks. The cafés and restaurants offer
different tastes from local and international cuisines,
with indoor and alfresco dining areas overlooking
Hyde Out’s scenic landscapes and beautiful lake.',
                'type' => 'content',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 10:48:58',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 68,
                'name' => 'Explore Elements eat and drink the promenade Location',
                'key' => 'explore_elements_eat_and_drink_the_promenade_location',
                'value' => 'text',
                'type' => 'text',
                'namespace' => 'explore_elements_eat_and_drink_the_promenade',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-21 11:34:39',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 69,
                'name' => 'Explore Elements eat and drink The food park Title 1',
                'key' => 'explore_elements_eat_and_drink_the_food_park_title1',
                'value' => 'THE FOOD PARK AREA',
                'type' => 'text',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 12:11:47',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 70,
                'name' => 'Explore Elements eat and drink The food park Content 1',
                'key' => 'explore_elements_eat_and_drink_the_food_park_content1',
                'value' => 'For the very first time in Egypt, Hyde Out introduces the global concept of park food at the heart of its captivating Picnic Park, surrounded by lush greenery and overlooking the serene lake. The designated Park Food Area is home to a myriad of colourful food trucks and carts that serve an array of delicious snacks, desserts and drinks.',
                'type' => 'content',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:39',
                'updated_at' => '2017-12-26 12:12:01',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 71,
                'name' => 'Explore Elements eat and drink The food park Image 1',
                'key' => 'explore_elements_eat_and_drink_the_food_park_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:47:46',
                'value_image_file_name' => 'food-park-show-01.jpg',
                'value_image_file_size' => 174304,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 12:47:46',
            ),
            70 => 
            array (
                'id' => 72,
                'name' => 'Explore Elements eat and drink The food park Logo 1',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:33:56',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:33:56',
            ),
            71 => 
            array (
                'id' => 73,
                'name' => 'Explore Elements eat and drink The food park Logo 2',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:35:10',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:35:10',
            ),
            72 => 
            array (
                'id' => 74,
                'name' => 'Explore Elements eat and drink The food park Logo 3',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo3',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:35:25',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:35:25',
            ),
            73 => 
            array (
                'id' => 75,
                'name' => 'Explore Elements eat and drink The food park Logo 4',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo4',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:36:02',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:36:02',
            ),
            74 => 
            array (
                'id' => 76,
                'name' => 'Explore Elements eat and drink The food park Logo 5',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo5',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:39:09',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:39:09',
            ),
            75 => 
            array (
                'id' => 77,
                'name' => 'Explore Elements eat and drink The food park Logo 6',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo6',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:41:06',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:41:06',
            ),
            76 => 
            array (
                'id' => 78,
                'name' => 'Explore Elements eat and drink The food park Title 2',
                'key' => 'explore_elements_eat_and_drink_the_food_park_title2',
                'value' => 'Take a break and gratify your taste buds in the heart of nature!',
                'type' => 'text',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:41:35',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 79,
                'name' => 'Explore Elements eat and drink The food park Image 2',
                'key' => 'explore_elements_eat_and_drink_the_food_park_image2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:42:18',
                'value_image_file_name' => 'food-park-show-02.jpg',
                'value_image_file_size' => 262432,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 12:42:18',
            ),
            78 => 
            array (
                'id' => 81,
                'name' => 'Explore Elements eat and drink The food park Logo 2-1',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:42:42',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:42:42',
            ),
            79 => 
            array (
                'id' => 82,
                'name' => 'Explore Elements eat and drink The food park Logo 2-2',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_2',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:44:10',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:44:10',
            ),
            80 => 
            array (
                'id' => 83,
                'name' => 'Explore Elements eat and drink The food park Logo 2-3',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_3',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:45:44',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:45:44',
            ),
            81 => 
            array (
                'id' => 84,
                'name' => 'Explore Elements eat and drink The food park Logo 2-4',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_4',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:45:22',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:45:22',
            ),
            82 => 
            array (
                'id' => 85,
                'name' => 'Explore Elements eat and drink The food park Logo 2-5',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_5',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:44:52',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:44:52',
            ),
            83 => 
            array (
                'id' => 86,
                'name' => 'Explore Elements eat and drink The food park Logo 2-6',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_6',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:44:32',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:44:32',
            ),
            84 => 
            array (
                'id' => 87,
                'name' => 'Explore Elements eat and drink The food park Logo 2-7',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_7',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:43:24',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:43:24',
            ),
            85 => 
            array (
                'id' => 88,
                'name' => 'Explore Elements eat and drink The food park Logo 2-8',
                'key' => 'explore_elements_eat_and_drink_the_food_park_logo2_8',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:43:03',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 12:43:03',
            ),
            86 => 
            array (
                'id' => 89,
                'name' => 'Explore Elements eat and drink the promenade Location',
                'key' => 'explore_elements_eat_and_drink_the_promenade_location',
                'value' => 'text',
                'type' => 'text',
                'namespace' => 'explore_elements_eat_and_drink_the_food_park',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-21 11:34:40',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 90,
                'name' => 'Explore Elements Shop Title 1',
                'key' => 'explore_elements_shop_title1',
                'value' => 'You won’t shop till you drop but you’ll find everything you need!',
                'type' => 'text',
                'namespace' => 'explore_elements_shop',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:05:00',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 91,
                'name' => 'Explore Elements shop Content 1',
                'key' => 'explore_elements_shop_content1',
                'value' => 'You don’t need to go out of your way or call it a day early, because at Hyde Out you’ll find all your shopping needs in one place! Don’t forget to pass by Hyde Out’s designated shopping area, where you can shop at
your own convenience and find everything you need for yourself, your kids and pets, and even the household.',
                'type' => 'content',
                'namespace' => 'explore_elements_shop',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-26 12:09:22',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 92,
                'name' => 'Explore Elements shop Image 1',
                'key' => 'explore_elements_shop_image1',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'explore_elements_shop',
                'created_at' => '2017-12-21 11:34:40',
                'updated_at' => '2017-12-25 13:44:48',
                'value_image_file_name' => 'shop-show-bg-01.jpg',
                'value_image_file_size' => 281697,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-25 13:44:48',
            ),
            90 => 
            array (
                'id' => 93,
                'name' => 'About Page Logo',
                'key' => 'about_page_logo',
                'value' => 'link',
                'type' => 'image',
                'namespace' => 'about_page',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 14:43:00',
                'value_image_file_name' => 'sponsor-logo-01.png',
                'value_image_file_size' => 18121,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 14:43:00',
            ),
            91 => 
            array (
                'id' => 94,
                'name' => 'explore elements play working hours2',
                'key' => 'explore_elements_play_working_hours2',
                'value' => 'Thursday: from 10:00 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => NULL,
                'updated_at' => '2017-12-25 11:48:52',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 95,
                'name' => 'explore elements play working hours3',
                'key' => 'explore_elements_play_working_hours3',
                'value' => 'Friday - Saturday: from 9:30 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_play',
                'created_at' => NULL,
                'updated_at' => '2017-12-25 11:49:22',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 96,
                'name' => 'Explore Elements Picnic Working Hours2',
                'key' => 'explore_elements_picnic_working_hours2',
                'value' => 'text',
                'type' => 'text',
                'namespace' => 'explore_elements_picnic',
                'created_at' => NULL,
                'updated_at' => NULL,
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 97,
                'name' => 'Explore Elements Exercise Working Hours2',
                'key' => 'explore_elements_exercise_working_hours2',
                'value' => 'Thursday: from 10:00 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 11:58:47',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 98,
                'name' => 'Explore Elements Exercise Working Hours3',
                'key' => 'explore_elements_exercise_working_hours3',
                'value' => 'Friday - Saturday: from 9:30 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 11:58:21',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 99,
                'name' => 'explore elements exercise provider Phone',
                'key' => 'explore_elements_exercise_provider_phone',
                'value' => '+20112212221',
                'type' => 'text',
                'namespace' => 'explore_elements_exercise',
                'created_at' => NULL,
                'updated_at' => NULL,
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 100,
                'name' => 'Explore Elements Pet Time Provider Phone',
                'key' => 'explore_elements_pet_time_provider_phone',
                'value' => '+20222122',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => NULL,
                'updated_at' => NULL,
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 101,
                'name' => 'Explore Elements Pet Time Provider site',
                'key' => 'explore_elements_pet_time_provider_site',
                'value' => 'https://www.k-9sense.com',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 11:27:26',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 103,
                'name' => 'explore elements pet time provider working hours1',
                'key' => 'explore_elements_pet_time_provider_working_hours1',
                'value' => 'Thursday: from 10:00 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 11:17:43',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 104,
                'name' => 'explore elements pet time provider working hours2',
                'key' => 'explore_elements_pet_time_provider_working_hours2',
                'value' => 'Friday - Saturday: from 9:30 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 11:18:08',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 105,
                'name' => 'Explore Elements entertain title1',
                'key' => 'explore_elements_entertain_title1',
                'value' => 'It’s Always Festive Time at Hyde Out!',
                'type' => 'text',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:14:30',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 106,
                'name' => 'explore elements entertain content1',
                'key' => 'explore_elements_entertain_content1',
                'value' => 'At Hyde Out we take entertainment very seriously, and you’re always going to find something interesting happening on our premises. Every weekend and holiday we host exclusive events and performances for kids and adults alike. Make sure to check our events calendar and book your tickets in advance – they sell out fast!',
                'type' => 'content',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:15:01',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 107,
                'name' => 'explore elements entertain image1',
                'key' => 'explore_elements_entertain_image1',
                'value' => 'image',
                'type' => 'image',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:15:54',
                'value_image_file_name' => 'entertain-show-bg-01.jpg',
                'value_image_file_size' => 197435,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:15:54',
            ),
            104 => 
            array (
                'id' => 108,
                'name' => 'explore elements entertain image2',
                'key' => 'explore_elements_entertain_image2',
                'value' => 'image',
                'type' => 'image',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:16:50',
                'value_image_file_name' => 'entertain-show-bg-02.jpg',
                'value_image_file_size' => 104780,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:16:50',
            ),
            105 => 
            array (
                'id' => 109,
                'name' => 'explore elements entertain provider content',
                'key' => 'explore_elements_entertain_provider_content',
                'value' => 'TICKET’S MARCHE is a designated zone
spread over 6000 sqm. In Hyde Out where
convenient games are available like Paintball,
Aqua Fight, Laser Fight, Bazooka Fight,
and which are targeting young professionals,
families and kids, university students and
youth.',
                'type' => 'content',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:17:50',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 110,
                'name' => 'Explore Elements Entertain Provider Logo',
                'key' => 'explore_elements_entertain_provider_logo',
                'value' => 'image',
                'type' => 'image',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:18:54',
                'value_image_file_name' => 'sponsor-logo-04.png',
                'value_image_file_size' => 7635,
                'value_image_content_type' => 'image/png',
                'value_image_updated_at' => '2017-12-26 10:18:54',
            ),
            107 => 
            array (
                'id' => 111,
                'name' => 'explore elements entertain provider working hours1',
                'key' => 'explore_elements_entertain_provider_working_hours1',
                'value' => 'Sunday - Wednesday: from 14:00 to 21:00',
                'type' => 'text',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:19:23',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 112,
                'name' => 'explore elements entertain provider working hours2',
                'key' => 'explore_elements_entertain_provider_working_hours2',
                'value' => 'Thursday: from 10:00 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:19:48',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 113,
                'name' => 'explore elements entertain provider working hours3',
                'key' => 'explore_elements_entertain_provider_working_hours3',
                'value' => 'Friday - Saturday: from 9:30 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:20:12',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 114,
                'name' => 'explore elements entertain provider working site',
                'key' => 'explore_elements_entertain_provider_site',
                'value' => 'www.ticketsmarche.com',
                'type' => 'text',
                'namespace' => 'explore_elements_entertain',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:20:31',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 115,
                'name' => 'Explore Elements-eat and drink Image1',
                'key' => 'explore_elements_eat_and_drink_image1',
                'value' => 'image',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:31:45',
                'value_image_file_name' => 'promenade-bg.jpg',
                'value_image_file_size' => 199160,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:31:45',
            ),
            112 => 
            array (
                'id' => 116,
                'name' => 'Explore Elements-eat and drink Image2',
                'key' => 'explore_elements_eat_and_drink_image2',
                'value' => 'image',
                'type' => 'image',
                'namespace' => 'explore_elements_eat_and_drink',
                'created_at' => NULL,
                'updated_at' => '2017-12-26 10:40:20',
                'value_image_file_name' => 'food-park-bg.jpg',
                'value_image_file_size' => 340605,
                'value_image_content_type' => 'image/jpeg',
                'value_image_updated_at' => '2017-12-26 10:40:20',
            ),
            113 => 
            array (
                'id' => 117,
                'name' => 'Explore Elements pet time Title 2',
                'key' => 'explore_elements_pet_time_title2',
                'value' => 'Bring your Furry Friends and Double your Fun!',
                'type' => 'text',
                'namespace' => 'explore_elements_pet_time',
                'created_at' => NULL,
                'updated_at' => NULL,
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 118,
                'name' => 'Explore Elements picnic Working Hours1',
                'key' => 'explore_elements_picnic_working_hours2',
                'value' => 'Sunday - Thursday: from 10:00 to 23:00',
                'type' => 'text',
                'namespace' => 'explore_elements_picnic',
                'created_at' => '2017-12-21 11:34:38',
                'updated_at' => '2017-12-26 10:06:13',
                'value_image_file_name' => NULL,
                'value_image_file_size' => NULL,
                'value_image_content_type' => NULL,
                'value_image_updated_at' => NULL,
            )
        ));
        
        
    }
}
